### ISSUE TITLE
Thunderbird thank you for submitting case is blank

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#866] opened 2020-03-05 18:21 UTC
After a user submits a case on [the help page](https://give.thunderbird.net/en-US/help/), users are sometimes receiving a blank white page. They then hit the back button and re-submit a case. This is creating duplicates in our queue.

**Comment by stephaniemcv** [comment] 2020-03-20 18:37
@hilarmstrong

**Comment by ryanleesipes** [comment] 2020-04-21 20:19
Should kick out to this page: https://give.thunderbird.net/en-US/help/?submitted=true - but can confirm it is doing this on Firefox 75, kicks me out to a blank page with the URL: https://webto.salesforce.com/servlet/servlet.WebToCase?encoding=UTF-8

Screenshot below:
![Screenshot from 2020-04-21 14-17-45](https://user-images.githubusercontent.com/2141621/79909936-09941e80-83db-11ea-8e63-eca5c436fe2e.png)

**Comment by cadecairos** [comment] 2020-04-22 19:09
I think I have a handle on what's causing this. [In this code we set the retURL form parameter](https://github.com/mozilla/donate-wagtail/blob/master/donate/templates/pages/core/contributor_support_page_master.html#L33) but I'm seeing it show up as `None` in the form HTML.

Looking into why..

**Comment by cadecairos** [comment] 2020-04-23 14:25
I've been digging into this some and found some interesting things. I know that the cause appears to be a mismatch in the reported root url path between the ContributorSupportPage model and the LandingPage model.

I ran a one-off dyno on our TB staging site, and dropped into a Django shell.

```
>>> from donate.core.models import ContributorSupportPage
>>> helppage = ContributorSupportPage.objects.first()
>>> helppage.url_path
'/thunderbird-donate/help/'
>>> helppage.get_parent().url_path
'/mozilla-donate/'
```

These url_path values are part of how Wagtail calculates the result of `get_full_url`, the method we're using to get the retURL value we pass to Salesforce when submitting a case.

In our LandingPage code we're overriding the model's slug value to hard code it to 'mozilla-donate` which I'm pretty sure is contributing to this.

**Comment by cadecairos** [comment] 2020-04-23 18:59
@TheoChevalier I spent all day tracing this bug, and I think I found the culprit:

Our `LandingPage` class [hard codes it's slug value to 'mozilla-donate'](https://github.com/mozilla/donate-wagtail/blob/2bbfd8fe5164743d4f42ad38db67695c49434ddc/donate/core/models.py#L229-L237). The assumption hinted to in the code comment that "this slug isn't used anywhere" is incorrect, as it's part of how Wagtail resolved full urls. 

Wagtail-pontoon-localize and mozillal10n/thunderbird-donate-content appear to break this for the help page on thunderbird as it's filed under a directory "thunderbird-donate" which seems to change the slug of the page when it syncs, breaking this URL resolution and thus breaking the `retURL` hidden input value.

Do you think it's possible to rename this directory and update the slug without breaking anything?

**Comment by TheoChevalier** [comment] 2020-04-24 10:32
@cadecairos 
Wow, that’s bad. This folder name is automatically generated by wagtail-pontoon-localize, I have no idea how it can be updated. The only thing I know is this must be done before I open the project to more locales, as changing the path will require every file in this folder to be retranslated. And this is only acceptable while I’m testing with French.

Do we have to rename this folder too? https://github.com/mozilla-l10n/mozilla-donate-content/tree/master/templates/pages/mozilla-donate If there’s any risk it bites us back later, I’d strongly push for updating it now

**Comment by cadecairos** [comment] 2020-04-27 15:49
I'm not sure how it's even generating that path. 

@kaedroho do you know why we might have ended up with one page in the site having an incorrect path in the translations repo? (see [this comment](https://github.com/mozilla/donate-wagtail/issues/866#issuecomment-618594271))

Any advice on how to remedy it?

**Comment by kaedroho** [comment] 2020-04-30 08:40
Hi @TheoChevalier and @cadecairos 

The folder name is generated from the URL path when the page is first submitted to Pontoon, this is stored in ``PontoonResource.path``.

Note that this path is never updated, even if the page is moved or the slug is changed. I implemented it like this because it's possible that a page might be moved at the same time translations were submitted for it in Pontoon and thought this might lead to those translations being lost.

However, this path is only used for looking up the page. When it creates a translation it always copies the source again and only replaces the fields that are translatable, so I'm not sure how `wagtail-localize-pontoon` would be setting the URL path like this. I think it's most likely that logic on `LandingPage` (when I wrote that, I didn't know there would be another site).

Something like this might fix it:

```python
    def save(self, *args, **kwargs):
        # This slug isn't used anywhere but it does need to be unique for each language
        if not self.is_source_translation:
            source_translation = self.get_translations().filter(is_source_translation=True)
            self.slug = source_translation.slug + '-' + self.locale.language_code

        super().save(*args, **kwargs)
```

> Do we have to rename this folder too? https://github.com/mozilla-l10n/mozilla-donate-content/tree/master/templates/pages/mozilla-donate If there’s any risk it bites us back later, I’d strongly push for updating it now

To do this, you can change the `path` in the `PontoonResource` model then resync and it should rename it for you. This should rename all the translations as well. I'm not sure how Pontoon will handle this though.

**Comment by cadecairos** [comment] 2020-05-13 19:53
I've manually updated the PontoonResource row for the help page to have the right slug, and the page slug (they're both "mozilla-donate" now, to match the slug of the default page) and then I forced a resync.

https://github.com/mozilla-l10n/thunderbird-donate-content/commit/cad9183e1fa0d0483579fccd4cc540c930f0eb32

I think it's fixed now. Doesn't explain how we got in this state to begin with though.

**Comment by cadecairos** [comment] 2020-05-13 20:17
> Do we have to rename this folder too? https://github.com/mozilla-l10n/mozilla-donate-content/tree/master/templates/pages/mozilla-donate If there’s any risk it bites us back later, I’d strongly push for updating it now

We should not have to update that. 

@TheoChevalier with the Database records corrected, and the folder updated thanks to the sync, I guess we now have to update the project in Pontoon?

**Comment by TheoChevalier** [comment] 2020-05-13 20:32
> We should not have to update that.

Nice :)

> @TheoChevalier with the Database records corrected, and the folder updated thanks to the sync, I guess we now have to update the project in Pontoon?

It should have happened automatically, but I’ve noticed it’s choking up on file renames lately (at least for projects using .toml config files). Generally a force sync by Pontoon devs fixes this, I’ll ping Matjaz tomorrow

**Comment by TheoChevalier** [comment] 2020-05-14 13:50
We’re all good Pontoon-wise

**Comment by cadecairos** [comment] 2020-05-14 14:21
Excellent, Marking this as resolved. 

Thanks for the pointer to `PontoonResource` @kaedroho!

**Comment by hilarmstrong** [comment] 2020-05-15 16:05
Just tested this in French, Spanish, and German, and the French page is still coming up blank. Also, the Spanish page is not localized--the paragraphs of text are in English.

**Comment by TheoChevalier** [comment] 2020-05-15 16:50
> Just tested this in French, Spanish, and German, and the French page is still coming up blank. 

I can confirm French is still broken, I guess we will have to reopen this ticket, then

> Also, the Spanish page is not localized--the paragraphs of text are in English.

This, however, is expected, as these strings are yet to be translated in Pontoon

**Comment by phildexter** [comment] 2020-05-19 16:25
This work will be tackled in #977 - moving this to closed.

**Closed by phildexter** 2020-05-19 16:25 UTC
Labels: bug, engineering
