### ISSUE TITLE
Other amount value clears out if you change frequency

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#372] opened 2019-10-02 23:40 UTC
If you enter a value into the other amount box and then choose a different frequency radio button, the value disappears.

**Comment by solarissmoke** [comment] 2019-10-10 08:10
I'm not able to reproduce this on staging - it might have been resolved with other tweaks to the "other amount" field behaviour.

**Closed** 2020-02-25 18:43 UTC
Labels: engineering
