### ISSUE TITLE
Spike: Determine if cors environment variables are needed for donate/thunderbird

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/donate-wagtail#1436] opened 2021-05-04 19:21 UTC
After an environment variable audit, it looks like we're not using the environment variables that are being set to handle CORS. We need to determine if these are being used in a package somewhere, and if not, remove them OR better yet, add in CORS support with the django-cors-headers package.

**Comment by danielfmiranda** [comment] 2022-01-25 01:00
Hi @Pomax! I have a quick question regarding this ticket:

I looked through the code and through heroku env variables and can confirm that we do not seem to use any CORS related ones on this app.

If I am not mistaking, I believe we are instead using the CSP_SCRIPT_SRC environment variable. 

Since we are using that for security regarding scripts, should I just remove the env variables relating to CORS and close this ticket? Or, do you think we should move forward for implementing the django-cors-headers package like mentioned in the ticket description? 

Thanks!

**Comment by Pomax** [comment] 2022-01-26 23:16
remember that not all vars are in our code, some are looked for by things like django, whitenoise, etc.

**Comment by danielfmiranda** [comment] 2022-03-01 00:16
Dependencies to check/checked:

- [ ] babel
- [ ] basket-client
- [ ] boto3
- [ ] braintree
- [ ] dj-database-url
- [ ] django-configurations
- [ ] django-countries
- [ ] django-csp
- [ ] django-environ
- [ ] django-redis
- [ ] django-rq
- [ ] django-storages
- [ ] django
- [ ] factory-boy
- [ ] freezegun
- [ ] gunicorn
- [ ] lxml
- [ ] mailchimp-marketing
- [ ] mozilla-django-oidc
- [ ] psycopg2-binary
- [ ] pygit2
- [ ] pysilverpop
- [ ] requests
- [ ] rq
- [ ] scout-apm
- [ ] sentry-sdk
- [ ] stripe
- [ ] wagtail-ab-testing
- [ ] wagtail-factories
- [ ] wagtail-localize
- [ ] wagtail-localize-git
- [ ] wagtail
- [ ] whitenoise

**Comment by danielfmiranda** [comment] 2022-03-01 01:07
Hi Everyone! 

After taking a look at the docs for all the requirements above (and double checking the one marked as "Maybe"), I could not seem to find anything that had a hard dependency for the specific CORS environment variables mentioned above.

To then test this, I created a review app here https://donate-wagta-updated-er-tq4tjg.herokuapp.com/en-US/

When I went to delete these variables from the heroku settings, I found that these actually were both not set for any review apps *at all*. I then tested both paypal and credit card flows and confirmed there were no changes, everything worked as expected.

I then removed both variables from the **staging** site, and was able to complete both flows without problem as well. I then added them back into the heroku settings for the staging site just in case.

This leads me to believe that these variables are not needed, and I believe we can remove these variables and close the ticket.

Tagging @Pomax to hear what you think/check if you might want to take a look at any of the docs above. Thank you!

**Comment by bheasman** [comment] 2022-03-14 19:41
Changes to be moved to staging - then we can close this ticket @danielfmiranda

**Comment by danielfmiranda** [comment] 2022-03-15 17:55
Can confirm that these env variables have been removed from staging, with no unintended effects

<img width="862" alt="Screen Shot 2022-03-15 at 10 53 15 AM" src="https://user-images.githubusercontent.com/18314510/158441114-dbfa7df0-086a-4b62-90c2-85711de78d9e.png">


Closing this ticket!

**Closed by danielfmiranda** 2022-03-15 17:55 UTC
Labels: backend, engineering, code cleanup
