### ISSUE TITLE
Field validation on custom amount field

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#285] opened 2019-09-30 15:14 UTC
When choosing a custom amount but leaving the value empty, clicking on either payment button should show some sort of error state before attempting to process.

@beccaklam Do we have error states for this?

- [ ] Verify this exists on the second screen

**Comment by beccaklam** [comment] 2019-09-30 18:20
I don't think there's a comp for that specific error. But I've attached the general error state styling below. In this case we could use the red border around the custom amount form field and the text below it could say _'Please add an amount'_ or _'Amount cannot be 0'_ or _'Amount must be greater than $3'_'.

**Mobile:**
![Screen Shot 2019-09-30 at 2 17 16 PM](https://user-images.githubusercontent.com/20977376/65904746-11339d80-e38d-11e9-90c2-c558d2085aae.png)

**Desktop:**
![Screen Shot 2019-09-30 at 2 17 31 PM](https://user-images.githubusercontent.com/20977376/65904754-1690e800-e38d-11e9-9183-7edeb1050f00.png)

**Comment by benhohner** [comment] 2021-03-29 21:37
@kristinashu is this still relevant? Do we still want it to have this behaviour?

**Comment by kristinashu** [comment] 2021-03-29 22:18
Yes, it does seem like we should have an error message for these cases. @benhohner is it possible to be specific? I.e.

- If custom amount box is selected but no amount is entered the error would say 'Please add an amount' 
- If someone enters 0 then error would say 'Amount cannot be 0'
- If someone enters an amount less that $3 then it would say 'Amount must be greater than $3.00'

Or should we have a generic one for all these cases? Perhaps 'Please enter an amount greater than $3.00'

@WillatMozFdn do you have any feedback on this copy?

**Comment by WillatMozFdn** [comment] 2021-03-30 14:07
Hmmm.  I'm leaning more towards sticking with a generic error message here (and the current "There were some errors with your form. Please amend the fields highlighted below" is acceptable in that regard) ...  because it seems there are a LOT of cases we would need to plan for here.  a) Every currency has a different minimum value (that's coded in a python file somewhere) so we can't just say "less than $3", there would need to be 20 different variants of that, one for each currency we accept ... b) also now with Wagtail pages (this is new since this bug was first filed) we do not/can not accept entry of custom amounts that include decimals (that is, you cannot donate $3.50) so we'd need to program for that, and c) all these error messages would need to be localized and programmed into the system.

We really don't receive many complaints at all about "your error messages did not help me fix the problem" ... so this does not appear to be a friction or pain point for our donors.  Given that setting up error messages for various scenarios in various currencies -- and in several different languages -- would get pretty complex pretty fast, it doesn't seem that the potential gains here from additional donations match up to the level of effort we're looking at here -- ???  We might want to icebox this one?

**Comment by kristinashu** [comment] 2021-03-30 14:42
Thanks Will! I really like the idea of keeping the error messages generic. I do think we should improve this use case tho. I recommend highlighting the "other amount" field in red and showing the red banner at the top with the message "There were some errors with your form. Please amend the fields highlighted below".

Screen cap from prod to show the red banner 
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/1068783/113007757-57f18780-912b-11eb-9f1c-be489b9cd871.png">

**Comment by WillatMozFdn** [comment] 2021-03-30 14:45
That sounds good to me, Kristina, thanks!  (Maybe we should say, ""There were some errors with your form submission." -- ??  Minor detail (adding the word "submission" at the end) but seems a little more accurate?  Probably doesn't matter a great deal, though.

**Comment by kristinashu** [comment] 2021-03-30 14:50
Sounds good, so the text should be "There were some errors with your form submission. Please amend the fields highlighted below."

@benhohner this should be ready for implementation now.

**Comment by jamilasnell** [comment] 2021-03-30 16:31
@kristinashu can you confirm that this text is for the amount page or for the details page? There are two different issues that are very similar and we want to avoid confusion here! @benhohner

**Comment by kristinashu** [comment] 2021-03-30 16:38
Oh idk. My only context is this ticket! My assumption was that it was for the amount page so let's keep it to that.
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/1068783/113024175-4dd78500-913b-11eb-9e88-d994ece3e8ec.png">

But the flow also isn't great on the details page but let's consider that out of scope. 
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/1068783/113024138-41ebc300-913b-11eb-9dbb-a97d39d4d4f2.png">

**Comment by alanmoo** [comment] 2021-03-30 16:49
Yeah, the idea was that they shouldn't be able to proceed to filling in details until a valid amount is filled in. The rest of the comps were just demonstrating error state.

**Comment by kristinashu** [comment] 2021-03-30 16:51
🙌

**Comment by benhohner** [comment] 2021-03-30 17:32
@danielfmiranda Looks like this ticket is just for the amount field
@kristinashu we're a bit concerned that message will be too long. We'll add some prototype screens to this issue so you can see.

**Comment by Pomax** [comment] 2021-04-26 21:13
@benhohner this issue has a "duplicate" label on it: is this really a duplicate (in which case we should probably close it) or does that label need to be removed?

**Comment by jamilasnell** [comment] 2021-06-24 19:12
@benhohner can you follow up on this issue? We think that this is a duplicate :/

**Comment by danielfmiranda** [comment] 2021-06-24 19:17
The ticket we believe this may be a duplicate of is: https://github.com/mozilla/donate-wagtail/issues/363, where Kalob and I added validation for this field and an error state when the user types something invalid

**Comment by Pomax** [comment] 2021-08-09 20:52
This work got done sometime in the past 1.5 years, so we can safely close this =)

**Closed by Pomax** 2021-08-09 20:52 UTC
Labels: duplicate, qa, engineering
