### ISSUE TITLE
CSP error in donate site

### ISSUE THREAD

**Issue by cdanfon** [mozilla/donate-wagtail#1679] opened 2022-07-26 15:12 UTC
Following completion of tickets #[1677](https://app.zenhub.com/workspace/o/mozilla/donate-wagtail/issues/1677) & #[1673](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/donate-wagtail/1673) the Digital Marketing team at TBX have tested the changes. 

An error is showing in the console for https://donate-wagtail.mofostaging.net/en-GB/

See attached ![Screenshot 2022-07-26 at 14.02.23.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/677a744f-59f9-4e3d-98cd-329680126024)

![Screenshot 2022-07-27 at 10.53.45.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/9d3e4b6c-ec35-4d84-b685-5fd82de4c84b)

**Comment by danielfmiranda** [comment] 2022-08-04 00:18
Closing as this is a duplicate of #1678

**Closed by danielfmiranda** 2022-08-04 00:18 UTC
Labels: bug, engineering, GA4
